# Generated by Django 3.2.18 on 2023-03-24 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todos_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='category',
            field=models.CharField(blank=True, default=datetime.datetime(2023, 3, 24, 6, 8, 26, 565876, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
