# Generated by Django 3.2.18 on 2023-03-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todos_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
