# Generated by Django 3.2.18 on 2023-03-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_alter_todos_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='category',
        ),
    ]
