# Generated by Django 3.2.18 on 2023-03-24 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_remove_todos_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
